### ISSUE TITLE
Plans to support Strapi v4

### ISSUE THREAD

**Issue by sj7272** [sarhugo/strapi-plugin-cloudflare-pages#1]
Is there any intention to upgrade for Strapi v4 support?

**Comment by sarhugo** [comment]
Yes, I hope soon enough

**Comment by duncandejong** [comment]
Any plans?

**Comment by sarhugo** [comment]
I can't give you an estimate right now. PR are welcome

**Comment by sarhugo** [comment]
Finally a release for v4 is done :rocket: 

Please check and let me know if you find any issue. I created a new v3 branch to keep the v3 compatible version, main branch will be used to maintain the v4.
